//OBJECTO WINDOW
//CONTIENE TODA LA INFORMACION QUE USAMOS DE FORMA DIRECTA CON JS
//ALERT(), PROMPT(), CONFIRM()

//WINDOW.BLUR() DETECTAMOS CUANDO EL USUARIO ABANDONA LA PESTAÑA

//WINDOW.FOCUS() DETECTAMOS CUANDO EL USUARIO HACE FOCO EN LA PESTAÑA

//WINDOW.ATOB() Y WINDOW.BTOA() PERMITE CODIFICAR Y DECODIFICAR EN BASE64

//WINDOW.SETTIMEOUT() ESTABLECER UN CRONOMETRO

//WINDOW.HISTORY() CONTIENE INFORMACIÓN DEL HISTORIAL. SE UTILIZA EN UNA DE LAS FORMAS DE CREAR SPA: APLICACIONES DE UNA SOLA PÁGINA


//NAVIGATOR
//CONTIENE INFORMACION PROPIA DEL NAVEGADOR

//NAVIGATOR.LANGUAGE NOS BRINDA EL IDIOMA CONFIGURADO EN EL NAVEGADOR

//Navigator.ONLINE //SABEMOS SI EL NAVEGADOR ESTA O NO CONECTADO A INTERNET

//NAVIGATOR.USERAGENT (SABER EL NAVEGADOR WEB, VERSIÓN, MOTOR, S.O., ETCÉTERA)
//RECOMIENDO EN SU LUGAR UTILIZAR A U-A PARSER JS

//NAVIGATOR.LOCATION INFORMACION COMPLETA DE LA URL
//LOCATION PUEDE UTILIZARSE DE FORMA DIRECTA

//NAVIGATOR.GEOLOCATION UBICACION DEL USUARIO //LO VEMOS MAS ADELANTE

//NAVIGATOR.SCREEN DEVUELVE INFORMACION DE LA PANTALLA DEL USUARIO
//LOCATION PUEDE UTILIZARSE DE FORMA DIRECTA

